import {
  ServiceCategory,
  ProfessionalProfile,
  ServiceRequest,
  Conversation,
  AppNotification,
  User,
  Review,
} from './types';

export const HAITIAN_ZONES = [
  'Delmas 33, Pòtoprens',
  'Pétion-Ville, Pòtoprens',
  'Delmas 75, Pòtoprens',
  'Carrefour, Route des Rails',
  'Tabarre, Boulevard 15 Octobre',
  'Sant Vil, Pòtoprens',
  'Kenscoff',
  'Kap Ayisyen, Sant Vil',
  'Trou-du-Nord, Nòdès',
  'Gonaïves',
  'Jakmèl, Sant Vil',
  'Okay (Les Cayes)',
];

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  { id: '1', slug: 'elektrisite', nameHt: 'Elektrisite', nameFr: 'Électricité', nameEn: 'Electrical', icon: 'Zap', count: 48, popular: true },
  { id: '2', slug: 'plonbri', nameHt: 'Plonbri', nameFr: 'Plomberie', nameEn: 'Plumbing', icon: 'Wrench', count: 35, popular: true },
  { id: '3', slug: 'mekanik', nameHt: 'Mekanik', nameFr: 'Mécanique', nameEn: 'Auto & Generator', icon: 'Settings', count: 29, popular: true },
  { id: '4', slug: 'reparasyon-kay', nameHt: 'Reparasyon kay', nameFr: 'Réparation maison', nameEn: 'Home Repair', icon: 'Hammer', count: 42, popular: true },
  { id: '5', slug: 'konstriksyon', nameHt: 'Konstriksyon', nameFr: 'Construction', nameEn: 'Construction', icon: 'Building2', count: 24, popular: true },
  { id: '6', slug: 'pentire', nameHt: 'Pentire', nameFr: 'Peinture', nameEn: 'Painting', icon: 'Paintbrush', count: 31, popular: true },
  { id: '7', slug: 'netwayaj', nameHt: 'Netwayaj', nameFr: 'Nettoyage', nameEn: 'Cleaning', icon: 'Sparkles', count: 27, popular: true },
  { id: '8', slug: 'jadinaj', nameHt: 'Jadinaj', nameFr: 'Jardinage', nameEn: 'Gardening', icon: 'Trees', count: 18 },
  { id: '9', slug: 'design-grafik', nameHt: 'Design grafik', nameFr: 'Design graphique', nameEn: 'Graphic Design', icon: 'Palette', count: 36, popular: true },
  { id: '10', slug: 'fotografi', nameHt: 'Fotografi', nameFr: 'Photographie', nameEn: 'Photography', icon: 'Camera', count: 22 },
  { id: '11', slug: 'videyo', nameHt: 'Videyo', nameFr: 'Vidéo', nameEn: 'Videography', icon: 'Video', count: 16 },
  { id: '12', slug: 'pwovese', nameHt: 'Pwofesè', nameFr: 'Professeur / Cours', nameEn: 'Tutoring', icon: 'GraduationCap', count: 54, popular: true },
  { id: '13', slug: 'tradiksyon', nameHt: 'Tradiksyon', nameFr: 'Traduction', nameEn: 'Translation', icon: 'Languages', count: 14 },
  { id: '14', slug: 'enformatik', nameHt: 'Enfòmatik', nameFr: 'Informatique & Réseau', nameEn: 'IT & Support', icon: 'Laptop', count: 38 },
  { id: '15', slug: 'enstalasyon-kamera', nameHt: 'Kamera sekirite', nameFr: 'Vidéosurveillance', nameEn: 'CCTV Cameras', icon: 'ShieldAlert', count: 19 },
  { id: '16', slug: 'frijide-ekondisyone', nameHt: 'Èkondisyone & Frijidè', nameFr: 'Climatisation', nameEn: 'AC & Refrigeration', icon: 'Wind', count: 25 },
  { id: '17', slug: 'kwizin', nameHt: 'Kwizin & Catering', nameFr: 'Cuisine', nameEn: 'Catering & Cooking', icon: 'Utensils', count: 21 },
  { id: '18', slug: 'bote-ak-swen', nameHt: 'Bote ak swen', nameFr: 'Beauté & Soins', nameEn: 'Beauty & Hair', icon: 'Scissors', count: 40 },
  { id: '19', slug: 'transpo', nameHt: 'Transpò & Livrezon', nameFr: 'Transport & Chauffeur', nameEn: 'Transport', icon: 'Truck', count: 33 },
  { id: '20', slug: 'lot-sevis', nameHt: 'Lòt sèvis', nameFr: 'Autres services', nameEn: 'Other Services', icon: 'Layers', count: 45 },
];

export const INITIAL_USER: User = {
  id: 'user_michel',
  name: 'Michel Jean',
  phone: '+509 4812 3456',
  email: 'michel.jean@servisht.com',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  location: 'Delmas 33, Pòtoprens',
  address: 'Delmas 33, Rue Charlemagne, Pòtoprens',
  role: 'customer',
  savedProIds: ['pro_1', 'pro_3'],
  defaultPayment: 'moncash',
};

export const INITIAL_PROS: ProfessionalProfile[] = [
  {
    id: 'pro_1',
    name: 'John Elektrik',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
    title: 'Elektrisyen Pwofesyonèl Batiman & Rezidansyèl',
    categorySlug: 'elektrisite',
    categoryName: 'Elektrisite',
    location: 'Delmas 33',
    fullAddress: 'Delmas 33, Rue Capois #14, Port-au-Prince',
    rating: 4.8,
    reviewsCount: 120,
    experienceYears: 7,
    isVerified: true,
    hasInsurance: true,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 12,
    startingPrice: 2500,
    about: 'Spesyalis nan tout kalite enstalasyon elektrik, depanaj kout-sikwi, bwat disjonktè, enstalasyon envètè, panno solè ak dèlko. Mwen travay ak zouti modèn selon nòm sekirite entènasyonal.',
    services: [
      { id: 's1', name: 'Enstalasyon nouvo fil & 6 priz', price: 3000, duration: '2 - 3 èdtan', description: 'Mete fil elektrik ak sekirite, ajoute 6 nouvo priz 110V/220V.' },
      { id: 's2', name: 'Depanaj kout-sikwi rapid', price: 2500, duration: '1 - 2 èdtan', description: 'Lokalizasyon ak reparasyon defo elektrik ki koupe kouran an.' },
      { id: 's3', name: 'Ranplasman bwat disjonktè', price: 5000, duration: '3 - 4 èdtan', description: 'Enstalasyon nouvo bwat pwoteksyon kont chaj elektrik.' },
      { id: 's4', name: 'Koneksyon Sistèm Envètè & Batri', price: 4500, duration: '2 - 4 èdtan', description: 'Koneksyon envètè 1.5kW rive 5kW ak batri Trojan/LiFePO4.' },
    ],
    serviceAreas: ['Delmas (tout zòn)', 'Pétion-Ville', 'Tabarre', 'Nazòn', 'Kenscoff'],
    portfolio: [
      {
        id: 'p1',
        title: 'Bwat disjonktè modèn Delmas 33',
        description: 'Renovasyon total yon bwat disjonktè ki te boule nan yon rezidans.',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
        date: 'Me 2024',
      },
      {
        id: 'p2',
        title: 'Enstalasyon limyè LED plafon',
        description: 'Mete limyè modèn ankadre ak switch entelijan nan salon.',
        image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
        date: 'Avril 2024',
      },
      {
        id: 'p3',
        title: 'Koneksyon Envètè 3.5kW',
        description: 'Sistèm sekou elektrik ak 4 batri 6V pou yon biwo nan Petyonvil.',
        image: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80',
        date: 'Mas 2024',
      }
    ],
    phone: '+509 3711 2233',
    whatsapp: '50937112233',
    completedJobsCount: 184,
  },
  {
    id: 'pro_2',
    name: 'Plonb Service',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    title: 'Plonbye Eksperimante • Tuyoteri & Rezèv Dlo',
    categorySlug: 'plonbri',
    categoryName: 'Plonbri',
    location: 'Delmas 31',
    fullAddress: 'Delmas 31, Rue Jacques 1er #8, Port-au-Prince',
    rating: 4.6,
    reviewsCount: 84,
    experienceYears: 5,
    isVerified: true,
    hasInsurance: false,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 20,
    startingPrice: 2000,
    about: 'Nou rezoud tout fuit dlo, nou enstale ponp dlo otomatik, chof-dlo solè, tòlèt ak lavabo modèn. Disponib 7 jou sou 7 pou ijans nan zòn metwopolitèn nan.',
    services: [
      { id: 's21', name: 'Reparasyon fuit dlo nan mi & anba tè', price: 2500, duration: '1 - 2 èdtan', description: 'Deteksyon ak ranplasman tiyo PVC oswa CPVC ki kase.' },
      { id: 's22', name: 'Enstalasyon Ponp Dlo & Rezèv', price: 4000, duration: '3 èdtan', description: 'Koneksyon ponp 0.5HP a 1HP ak tank dlo ak switch flote.' },
      { id: 's23', name: 'Debouche twalèt & lavabo', price: 2000, duration: '1 èdtan', description: 'Netwayaj ak debouche rapid san kraze tiyo.' },
    ],
    serviceAreas: ['Delmas', 'Pétion-Ville', 'Tabarre', 'Canapé-Vert'],
    portfolio: [
      {
        id: 'p21',
        title: 'Enstalasyon sistèm ponp otomatik',
        description: 'Mete ponp presyon ak tank rezèv pou yon bilding 2 etaj.',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
        date: 'Me 2024',
      }
    ],
    phone: '+509 3890 4455',
    whatsapp: '50938904455',
    completedJobsCount: 112,
  },
  {
    id: 'pro_3',
    name: 'Auto Master (Marc-Donald)',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80',
    title: 'Mekanisyen Jeneral & Dèlko Endistriyèl',
    categorySlug: 'mekanik',
    categoryName: 'Mekanik',
    location: 'Carrefour',
    fullAddress: 'Route des Rails, Carrefour, Port-au-Prince',
    rating: 4.7,
    reviewsCount: 112,
    experienceYears: 9,
    isVerified: true,
    hasInsurance: true,
    isFastResponse: false,
    isAvailable: true,
    distanceMinutes: 35,
    startingPrice: 3500,
    about: 'Reparasyon machin Japonè ak Ameriken (Toyota, Nissan, Ford, Honda), chanjman fren, motè, transmisyon, ak reparasyon dèlko Perkins, Cummins, ak Honda.',
    services: [
      { id: 's31', name: 'Dyagnostik Scanner ak Reparasyon', price: 3500, duration: '2 èdtan', description: 'Lekti kòd defo ak tcheke tout sistèm elektwonik machin lan.' },
      { id: 's32', name: 'Sèvis Antretyen Dèlko (Chanjman lwil/filtre)', price: 4000, duration: '2 èdtan', description: 'Ranplasman lwil, filtre lwil ak gazolin sou dèlko.' },
      { id: 's33', name: 'Ranplasman Plaquet Fren & Disk', price: 3000, duration: '1 - 2 èdtan', description: 'Mete nouvo fren orijinal devan ak dèyè.' },
    ],
    serviceAreas: ['Carrefour', 'Port-au-Prince', 'Delmas', 'Léogâne'],
    portfolio: [
      {
        id: 'p31',
        title: 'Revizyon motè Toyota Hilux',
        description: 'Chanjman kouwa distribisyon ak ponp dlo.',
        image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80',
        date: 'Avril 2024',
      }
    ],
    phone: '+509 4622 7890',
    whatsapp: '50946227890',
    completedJobsCount: 240,
  },
  {
    id: 'pro_4',
    name: 'Design Lakay',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    title: 'Designer Grafik & Idantite Vizyèl Biznis',
    categorySlug: 'design-grafik',
    categoryName: 'Design grafik',
    location: 'Pétion-Ville',
    fullAddress: 'Rue Rebecca, Pétion-Ville, Port-au-Prince',
    rating: 4.9,
    reviewsCount: 64,
    experienceYears: 4,
    isVerified: true,
    hasInsurance: false,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 15,
    startingPrice: 5000,
    about: 'Mwen kreye logo pwofesyonèl, afich, flyer pou rezo sosyal, bandwòl ak meni restoran pou biznis lokal an Ayiti ak nan dyaspora.',
    services: [
      { id: 's41', name: 'Pake Logo & Brandbook konplè', price: 7500, duration: '3 jou', description: 'Logo nan tout fòma (PNG, SVG, PDF) ak gid koulè ak tipografi.' },
      { id: 's42', name: 'Flyer Pwofesyonèl pou Rezo Sosyal', price: 2500, duration: '24 èdtan', description: 'Konsepsyon 2 afich pou Instagram ak Facebook.' },
    ],
    serviceAreas: ['Travay an liy toupatou an Ayiti', 'Pétion-Ville'],
    portfolio: [
      {
        id: 'p41',
        title: 'Idantite Vizyèl Restoran Lakay',
        description: 'Kreyasyon logo, meni ak konsepsyon anbalaj manje.',
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80',
        date: 'Me 2024',
      }
    ],
    phone: '+509 3100 8899',
    whatsapp: '50931008899',
    completedJobsCount: 95,
  },
  {
    id: 'pro_5',
    name: 'Pwofesè Marie (Marie-Claire)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    title: 'Pwofesè Matematik, Fizik & Preparasyon Bakalawrya',
    categorySlug: 'pwovese',
    categoryName: 'Pwofesè',
    location: 'Tabarre',
    fullAddress: 'Tabarre 27, Port-au-Prince',
    rating: 4.9,
    reviewsCount: 142,
    experienceYears: 10,
    isVerified: true,
    hasInsurance: false,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 25,
    startingPrice: 3000,
    about: 'Lisansye nan Syans Egzat nan Inivèsite Leta d Ayiti. Mwen bay kou patikilye lakay ou oswa sou Zoom pou elèv 9èm AF, Nsg I rive Nsg IV (Bakaloreya). Pousantaj reyisit elèv mwen yo depase 95%.',
    services: [
      { id: 's51', name: 'Sesyon Kou Patikilye (2 èdtan)', price: 3000, duration: '2 èdtan', description: 'Kou entansif nan Matematik, Fizik oswa Chimi.' },
      { id: 's52', name: 'Pake Preparasyon Egzamen Ofisyèl (Pa semèn)', price: 8000, duration: '3 sesyon / semèn', description: 'Egzèsis pratik, ansyen tèks egzamen leta ak sipò pèsonalize.' },
    ],
    serviceAreas: ['Tabarre', 'Delmas', 'Pétion-Ville', 'An liy (Zoom)'],
    portfolio: [
      {
        id: 'p51',
        title: 'Gwoup elèv ki reyisi Bakalawrya 2023',
        description: 'Tout 18 elèv mwen yo te reyisi egzamen leta ak bon nòt.',
        image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80',
        date: 'Jiyè 2023',
      }
    ],
    phone: '+509 3422 1199',
    whatsapp: '50934221199',
    completedJobsCount: 310,
  },
  {
    id: 'pro_6',
    name: 'Tech Solution HT (Evens)',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    title: 'Teknisyen Kamera Sekirite & Rezo Entènèt Starlink',
    categorySlug: 'enstalasyon-kamera',
    categoryName: 'Kamera sekirite',
    location: 'Delmas 75',
    fullAddress: 'Delmas 75, Rue Catalpa #22, Port-au-Prince',
    rating: 4.8,
    reviewsCount: 58,
    experienceYears: 6,
    isVerified: true,
    hasInsurance: true,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 18,
    startingPrice: 4000,
    about: 'Enstalasyon sistèm kamera siveyans HD & 4K (Dahua, Hikvision), konfigirasyon antèn Starlink ak rezo Wi-Fi ki kouvri tout kay oswa biznis ou.',
    services: [
      { id: 's61', name: 'Enstalasyon Starlink & Wi-Fi Mesh', price: 5000, duration: '2 - 3 èdtan', description: 'Pozisyon antèn sou do kay, pase fil pwòp, ak konfigirasyon router.' },
      { id: 's62', name: 'Enstalasyon 4 Kamera Sekirite ak DVR', price: 8000, duration: '4 - 5 èdtan', description: 'Mete kamera ak vizyon lannwit, koneksyon sou telefòn ou pou gade an dirèk.' },
    ],
    serviceAreas: ['Delmas', 'Pétion-Ville', 'Tabarre', 'Kenscoff', 'Sant Vil'],
    portfolio: [
      {
        id: 'p61',
        title: 'Sistèm sekirite 8 kamera nan yon magazen',
        description: 'Koneksyon DVR sou rezo ak alèt sou telefòn.',
        image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&auto=format&fit=crop&q=80',
        date: 'Me 2024',
      }
    ],
    phone: '+509 3660 7711',
    whatsapp: '50936607711',
    completedJobsCount: 140,
  },
  {
    id: 'pro_7',
    name: 'Koulè Pwòp (Gary Paint)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
    title: 'Mèt Pent & Finisyon Batiman',
    categorySlug: 'pentire',
    categoryName: 'Pentire',
    location: 'Pétion-Ville',
    fullAddress: 'Morne Lazare, Pétion-Ville, Port-au-Prince',
    rating: 4.7,
    reviewsCount: 73,
    experienceYears: 8,
    isVerified: true,
    hasInsurance: true,
    isFastResponse: false,
    isAvailable: true,
    distanceMinutes: 22,
    startingPrice: 4500,
    about: 'Pentire anndan kou deyò kay, tèt kay, tretman imidite ak krak nan mi, penti dekoratif ak lank pou bwa.',
    services: [
      { id: 's71', name: 'Pentire 1 pyès kay (Salon oswa Chanm)', price: 4500, duration: '1 jou', description: 'Fwote mi, bouche twou ak mastike, 2 kouch penti bon kalite.' },
      { id: 's72', name: 'Tretman enpèmeyabilizasyon kont lapli', price: 7000, duration: '1 - 2 jou', description: 'Mete pwodwi enpèmeyab sou tèt kay pou anpeche dlo koule.' },
    ],
    serviceAreas: ['Pétion-Ville', 'Delmas', 'Montagne Noire', 'Kenscoff'],
    portfolio: [
      {
        id: 'p71',
        title: 'Finisyon kay 2 etaj nan Petyonvil',
        description: 'Penti ekstèn blan ak gri modèn.',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&auto=format&fit=crop&q=80',
        date: 'Mas 2024',
      }
    ],
    phone: '+509 3778 9900',
    whatsapp: '50937789900',
    completedJobsCount: 88,
  },
  {
    id: 'pro_8',
    name: 'ClimaTech HT (Woody)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop&q=80',
    title: 'Teknisyen Èkondisyone & Frijidè',
    categorySlug: 'frijide-ekondisyone',
    categoryName: 'Èkondisyone & Frijidè',
    location: 'Delmas 19',
    fullAddress: 'Delmas 19, Rue Sans-Fil #4, Port-au-Prince',
    rating: 4.8,
    reviewsCount: 90,
    experienceYears: 5,
    isVerified: true,
    hasInsurance: false,
    isFastResponse: true,
    isAvailable: true,
    distanceMinutes: 14,
    startingPrice: 3000,
    about: 'Netwayaj ac, chaje gaz R410A / R32, reparasyon frijidè ki pa glase, reparasyon konpresè ak enstalasyon ac nouvo.',
    services: [
      { id: 's81', name: 'Netwayaj konplè AC ak ponp dlo presyon', price: 3000, duration: '1 èdtan', description: 'Demontaj ak lave filtè, evaporatè ak kondansatè pou bay frechè maksimòm.' },
      { id: 's82', name: 'Tcheke fuit & Chajman gaz konplè', price: 4500, duration: '1 - 2 èdtan', description: 'Soude kote ki gen fuit la epi mete bon nivo gaz.' },
    ],
    serviceAreas: ['Delmas', 'Pétion-Ville', 'Nazòn', 'Tabarre'],
    portfolio: [
      {
        id: 'p81',
        title: 'Enstalasyon 3 AC Inverter 12,000 BTU',
        description: 'Mete aparèy yo ak switch pwoteksyon.',
        image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&auto=format&fit=crop&q=80',
        date: 'Avril 2024',
      }
    ],
    phone: '+509 4433 2211',
    whatsapp: '50944332211',
    completedJobsCount: 165,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    proId: 'pro_1',
    customerName: 'Jean-Baptiste M.',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'John se yon bon elektrisyen trè konpetan. Li te rive alè Delmas 33, rezoud kout-sikwi a anba 1 èdtan epi pri a te trè rezonab. Mwen rekòmande li 100%!',
    date: '10 Me 2024',
    proResponse: 'Mèsi anpil frè m! Se te yon plezi sèvi w.',
  },
  {
    id: 'rev_2',
    proId: 'pro_1',
    customerName: 'Claudette Pierre',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Enstalasyon disjonktè a fèt trè pwòp. Li te pran tan pou eksplike m kijan pou m jere chaj la pou l pa sote ankò.',
    date: '3 Me 2024',
  },
  {
    id: 'rev_3',
    proId: 'pro_1',
    customerName: 'Roseline Saint-Fleur',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    rating: 4.5,
    comment: 'Travay rapid e pwofesyonèl. Li respekte nòm yo e li te trè janti.',
    date: '24 Avril 2024',
  },
  {
    id: 'rev_4',
    proId: 'pro_2',
    customerName: 'Daniel Estimé',
    customerAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Fuit dlo anba douch la te yon gwo tèt chaje. Plonb Service te jwenn kote kase a san li pa bezwen kase tout mozayik yo.',
    date: '12 Me 2024',
  },
  {
    id: 'rev_5',
    proId: 'pro_3',
    customerName: 'Patrick V.',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Marc-Donald se pi bon mekanisyen dèlko mwen konnen nan Pòtoprens. Li repare dèlko 25kVA nou an nan menm jounen an.',
    date: '15 Me 2024',
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 'req_101',
    referenceCode: 'SHT-8821',
    customerId: 'user_michel',
    customerName: 'Michel Jean',
    customerPhone: '+509 4812 3456',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    proId: 'pro_1',
    proName: 'John Elektrik',
    proAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Elektrisite',
    serviceName: 'Enstalasyon elektrik',
    description: 'M bezwen enstale nouvo fil elektrik nan salon mwen ak mete 6 priz adisyonèl pou òdinatè ak televizyon.',
    address: 'Delmas 33, Rue Capois #14',
    date: 'Madi 14 Me 2024',
    timeSlot: '10:00 AM - 12:00 PM',
    priceEstimate: 3000,
    status: 'accepted',
    photos: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80'],
    notes: 'Kite m konnen si ou bezwen m achte fil yo anvan.',
    createdAt: '12 Me 2024 • 10:28 AM',
    paymentMethod: 'moncash',
    paid: false,
  },
  {
    id: 'req_102',
    referenceCode: 'SHT-8790',
    customerId: 'user_michel',
    customerName: 'Michel Jean',
    customerPhone: '+509 4812 3456',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    proId: 'pro_3',
    proName: 'Auto Master (Marc-Donald)',
    proAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Mekanik',
    serviceName: 'Reparasyon machin',
    description: 'Fren devan machin mwen an ap fè gwo bri lè m ap frennen. Bezwen tcheke plaquet ak disk.',
    address: 'Delmas 33, Rue Capois',
    date: 'Lendi 20 Me 2024',
    timeSlot: '2:00 PM - 4:00 PM',
    priceEstimate: 3500,
    status: 'pending',
    photos: [],
    createdAt: '13 Me 2024 • 2:15 PM',
    paymentMethod: 'natcash',
    paid: false,
  },
  {
    id: 'req_103',
    referenceCode: 'SHT-8645',
    customerId: 'user_michel',
    customerName: 'Michel Jean',
    customerPhone: '+509 4812 3456',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    proId: 'pro_7',
    proName: 'Koulè Pwòp (Gary Paint)',
    proAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Pentire',
    serviceName: 'Kolè kay & Pentire Salon',
    description: 'Pentire mi salon an ak koulè blan pèl, kouvri tach imidite.',
    address: 'Delmas 33, Rue Capois',
    date: 'Samdi 25 Me 2024',
    timeSlot: '9:00 AM - 1:00 PM',
    priceEstimate: 4500,
    status: 'completed',
    photos: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&auto=format&fit=crop&q=80'],
    createdAt: '01 Me 2024',
    paymentMethod: 'moncash',
    paid: true,
    ratingGiven: 5,
  },
  {
    id: 'req_104',
    referenceCode: 'SHT-8512',
    customerId: 'user_michel',
    customerName: 'Michel Jean',
    customerPhone: '+509 4812 3456',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    proId: 'pro_2',
    proName: 'Plonb Service',
    proAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Plonbri',
    serviceName: 'Reparasyon tiyo tank dlo',
    description: 'Tiyo ki konekte tank anlè kay la te kase.',
    address: 'Delmas 33',
    date: '10 Avril 2024',
    timeSlot: '11:00 AM - 1:00 PM',
    priceEstimate: 2200,
    status: 'cancelled',
    photos: [],
    createdAt: '09 Avril 2024',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    proId: 'pro_1',
    proName: 'John Elektrik',
    proAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Elektrisite',
    isOnline: true,
    lastMessage: 'Wi, 10è bon pou mwen.',
    lastMessageTime: '10:34 AM',
    unreadCount: 1,
    messages: [
      {
        id: 'm1',
        sender: 'pro',
        text: 'Bonjou Michel! Mwen resevwa demann ou a. Ki kalite enstalasyon ou bezwen egzakteman?',
        timestamp: '10:30 AM',
      },
      {
        id: 'm2',
        sender: 'customer',
        text: 'Bonjou! Se nouvo fil elektrik ak 6 priz m bezwen nan salon an.',
        timestamp: '10:32 AM',
      },
      {
        id: 'm3',
        sender: 'pro',
        text: 'Ok, mwen disponib madi maten. Èske 10è bon pou ou?',
        timestamp: '10:33 AM',
      },
      {
        id: 'm4',
        sender: 'customer',
        text: 'Wi, 10è bon pou mwen.',
        timestamp: '10:34 AM',
      },
    ],
  },
  {
    id: 'conv_2',
    proId: 'pro_3',
    proName: 'Auto Master (Marc-Donald)',
    proAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Mekanik',
    isOnline: false,
    lastMessage: 'Mwen voye estimasyon pou plaquet fren yo ba ou.',
    lastMessageTime: 'Yer',
    unreadCount: 0,
    messages: [
      {
        id: 'm21',
        sender: 'customer',
        text: 'Bonswa mèt Marc, èske w gen tan tcheke fren yo pou mwen?',
        timestamp: 'Yer 3:15 PM',
      },
      {
        id: 'm22',
        sender: 'pro',
        text: 'Mwen voye estimasyon pou plaquet fren yo ba ou.',
        timestamp: 'Yer 3:25 PM',
      },
    ],
  },
  {
    id: 'conv_3',
    proId: 'pro_4',
    proName: 'Design Lakay',
    proAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    proCategory: 'Design grafik',
    isOnline: true,
    lastMessage: 'Premye pwopozisyon logo a prèske prè!',
    lastMessageTime: '3 Me',
    unreadCount: 0,
    messages: [
      {
        id: 'm31',
        sender: 'pro',
        text: 'Premye pwopozisyon logo a prèske prè!',
        timestamp: '3 Me',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    type: 'request_accepted',
    title: 'John Elektrik te aksepte demann ou a',
    message: 'Travay enstalasyon elektrik la pwograme pou Madi 14 Me a 10:00 AM.',
    timestamp: '10:30 AM',
    isRead: false,
    requestId: 'req_101',
  },
  {
    id: 'notif_2',
    type: 'new_message',
    title: 'Nouvo mesaj soti nan John Elektrik',
    message: '"Ok, mwen disponib madi maten. Èske 10è bon pou ou?"',
    timestamp: '10:32 AM',
    isRead: false,
    targetScreen: 'chat',
  },
  {
    id: 'notif_3',
    type: 'request_created',
    title: 'Demann ou a voye bay John Elektrik',
    message: 'Nou voye rezime demann SHT-8821 la bay pwofesyonèl la.',
    timestamp: '10:28 AM',
    isRead: true,
    requestId: 'req_101',
  },
  {
    id: 'notif_4',
    type: 'payment_confirmed',
    title: 'Peman ou a konfime',
    message: 'Peman $4,500 HTG pou travay penti a fèt avèk siksè sou MonCash.',
    timestamp: '12 Me 2024',
    isRead: true,
  },
];

export const FAQ_LIST = [
  {
    qHt: 'Kijan SÈVIS HT fonksyone?',
    aHt: 'SÈVIS HT se yon platfòm ki konekte ou ak pi bon pwofesyonèl lokal an Ayiti. Ou ka chèche sèvis ou bezwen an, gade pwofil, pri ak evalyasyon reyèl, mande yon sèvis dirèkteman, oswa kontakte pwofesyonèl la sou WhatsApp.',
  },
  {
    qHt: 'Kijan pwofesyonèl yo verifye?',
    aHt: 'Ekip SÈVIS HT verifye pyès idantite (NIF/CIN), adrès kote y ap travay, referans kliyan anvan, ak konpetans pwofesyonèl la anvan li resevwa badj vèt "Pwofesyonèl Verifye".',
  },
  {
    qHt: 'Ki mòd peman ki disponib?',
    aHt: 'Ou ka peye dirèkteman ak Digicel MonCash, Natcom NatCash, oswa an lajan kach (cash in hand) lè travay la fini nèt epi ou satisfè.',
  },
  {
    qHt: 'Kijan m ka vin yon pwofesyonèl sou platfòm nan?',
    aHt: 'Ale nan meni Pwofil la, klike sou "Mòd Pwofesyonèl" oswa "Vin yon Pwofesyonèl", ranpli enfòmasyon sou metye w, zòn ou kouvri ak pri w yo, epi telechaje foto travay ou deja fè.',
  },
  {
    qHt: 'Èske m ka anile yon demann?',
    aHt: 'Wi, ou ka anile yon demann nenpòt lè anvan pwofesyonèl la kòmanse travay la, dirèkteman nan paj "Demann mwen".',
  },
];
