export const HAITIAN_ZONES = [
  "Port-au-Prince",
  "Delmas",
  "Pétion-Ville",
  "Carrefour",
  "Tabarre",
  "Cap-Haïtien",
  "Les Cayes",
  "Gonaïves",
  "Jacmel",
  "Saint-Marc",
  "Trou du Nord"
];

export const MOCK_CATEGORIES = [
  { id: "elektriyen", name: "Elektriyen", icon: "Zap" },
  { id: "plonbye", name: "Plonbye", icon: "Wrench" },
  { id: "mekanisyen", name: "Mekanisyen", icon: "Car" },
  { id: "design-grafik", name: "Design grafik", icon: "Palette" },
  { id: "pwofese", name: "Pwofesè", icon: "BookOpen" },
  { id: "netwayaj", name: "Netwayaj", icon: "Sparkles" },
  { id: "chofe-prive", name: "Chofè prive", icon: "UserCheck" },
  { id: "konstriksyon", name: "Konstriksyon", icon: "Hammer" },
  { id: "tifinaj", name: "Tifinaj", icon: "Scissors" }
];

export const MOCK_PROS: any[] = [];

export const TRANSLATIONS: Record<string, any> = {
  popularServices: "Sèvis popilè",
  featuredPros: "Pwofesyonèl toupre w",
  seeAll: "Wè tout",
  navHome: "Akèy",
  navSearch: "Rechèch",
  navRequests: "Demann",
  navMessages: "Mesaj",
  navProfile: "Profil",
  allCategories: "Sèvis yo",
  searchServicePlaceholder: "Chèche sèvis, pwofesyonèl...",
  prosAvailable: "pwofesyonèl disponib",
  greetingMorning: "Bonjou",
  loginTitle: "Kontinye konekte",
  phoneLabel: "Nimewo telefòn",
  passwordLabel: "Mopas",
  forgotPassword: "Ou bliye mopas ou?",
  btnLogin: "Login",
  orDivider: "oswa",
  continueWithGoogle: "Kontinye ak Google",
  noAccountYet: "Pa gen kont?",
  createOne: "Kreye youn",
  registerTitle: "Kreye yon kont",
  fullNameLabel: "Non konplè",
  fullNamePlaceholder: "Eks: Jean Baptiste",
  emailLabel: "Adrès imèl",
  emailPlaceholder: "zanmi@egzanp.com",
  confirmPasswordLabel: "Konfime mopas la",
  agreeTerms: "Mwen aksepte kondisyon yo",
  btnRegister: "Enskri",
  otpTitle: "Verifikasyon OTP",
  otpDesc: "Antre kòd verifikasyon ou resevwa a",
  btnVerify: "Verifye",
  resendCode: "Renvoye kòd la",
  filterAll: "Tout",
  filterAvailable: "Disponib",
  filterTopRated: "Pi wo rated",
  filterNearMe: "Tò pre w",
  noResultsTitle: "Okenn pwofesyonèl pa disponib",
  noResultsDesc: "Pa gen pwofesyonèl ki anrejistre nan kategori sa a pou kounye a.",
  yearsExperience: "ane eksperyans",
  changeZone: "Chanje zòn",
  notificationsTitle: "Nòtifikasyon",
  onboarding1Title: "Byenveni sou SÈVIS HT",
  onboarding1Desc: "Jwenn pwofesyonèl ou bezwen, toupre w, rapid e fasil.",
  btnSkip: "Sote",
  tagline: "Jwenn pwofesyonèl ou bezwen, toupre w, rapid e fasil.",
  btnStart: "Kòmanse",
  howItWorks: "Dekouvri kijan li mache",
  btnNext: "Kòmanse",
  profileTitle: "Profil",
  settings: "Paramèt",
  logout: "Dekonekte",
  myRequestsTitle: "Demann mwen",
  searchTitle: "Chèche yon sèvis...",
  popularSearches: "Rechèch popilè"
};
