const PASSWORD_REQUIREMENTS = {
  MIN_LENGTH: 12,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBERS: true,
  REQUIRE_SPECIAL_CHARS: true,
};

const PASSWORD_REGEX =
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$/;

const JWT_CONFIG = {
  EXPIRATION: '7d',
  REFRESH_EXPIRATION: '30d',
};

const OTP_CONFIG = {
  LENGTH: 6,
  EXPIRATION_MINUTES: 10,
  MAX_ATTEMPTS: 5,
};

const PASSWORD_RESET_CONFIG = {
  TOKEN_LENGTH: 32,
  EXPIRATION_MINUTES: 30,
};

const RATE_LIMITS = {
  AUTH: { windowMs: 15 * 60 * 1000, max: 10 },
  OTP: { windowMs: 10 * 60 * 1000, max: 5 },
  SERVICE: { windowMs: 15 * 60 * 1000, max: 50 },
  MESSAGE: { windowMs: 10 * 60 * 1000, max: 100 },
  GENERAL: { windowMs: 15 * 60 * 1000, max: 100 },
};

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  PROFESSIONAL: 'PROFESSIONAL',
  CUSTOMER: 'CUSTOMER',
};

const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  DELETED: 'DELETED',
};

const SERVICE_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

module.exports = {
  PASSWORD_REQUIREMENTS,
  PASSWORD_REGEX,
  JWT_CONFIG,
  OTP_CONFIG,
  PASSWORD_RESET_CONFIG,
  RATE_LIMITS,
  ROLES,
  ACCOUNT_STATUS,
  SERVICE_STATUS,
  PAYMENT_STATUS,
};
